#pragma once

#include "../network/Host.h"
#include "../network/NetworkTypes.h"
#include "../network/OnlineComponent.h"
#include "../network/OnlineSystem.h"
#include "../network/ServerClientData.h"

#include "../network/packet/CapturePointPacket.h"
#include "../network/packet/ControllerPacket.h"
#include "../network/packet/JoinPacket.h"
#include "../network/packet/MessagePacket.h"
#include "../network/packet/Packet.h"
#include "../network/packet/PacketTypes.h"
#include "../network/packet/QuitPacket.h"
#include "../network/packet/StatePacket.h"
#include "../network/packet/TeamChangePacket.h"
#include "../network/packet/TimestampPacket.h"
#include "../network/packet/WeaponChangePacket.h"
#include "../network/packet/WelcomePacket.h"
#include "../network/packet/AcknowledgePacket.h"
#include "../network/packet/NameTagPacket.h"